# Author: Alejandro Galue <agalue@opennms.org>
#
# The solution was designed to be executed from the OpenNMS server,
# as the Cassandra VMs won't have public IP addresses.
#
# WARNING:
# - Make sure cassandra_servers.hosts is consistent with the size
#   of cassandra_ip_addresses in vars.tf.
# - The solution uses DNS, to avoid having the IP addresses here.
---
all:
  vars:
    ansible_user: agalue
    ansible_port: 22
    ansible_private_key_file: global-ssh-key
    timezone: America/New_York
    tss_strategy: newts # Options: newts, cortex
    snmp:
      syscontact: Alejandro Galue <agalue@opennms.org>
      syslocation: Azure
    sysctl_config:
      net.ipv4.tcp_keepalive_time: 60
      net.ipv4.tcp_keepalive_probes: 3
      net.ipv4.tcp_keepalive_intvl: 10
      net.core.rmem_max: 16777216
      net.core.wmem_max: 16777216
      net.core.rmem_default: 16777216
      net.core.wmem_default: 16777216
      net.core.optmem_max: 40960
      net.ipv4.tcp_rmem: 4096 87380 16777216
      net.ipv4.tcp_wmem: 4096 65536 16777216
      net.ipv4.tcp_window_scaling: 1
      net.core.netdev_max_backlog: 2500
      net.core.somaxconn: 65000
      vm.swappiness: 1
      vm.zone_reclaim_mode: 0
      vm.max_map_count: 1048575
  children:
    onms_servers:
      vars:
        target_ipv4: '{{ ansible_eth0.ipv4.address }}'
        opennms:
          repo: stable
          interval: 30000 # For Polling and Data Collection
          timeseries:
            # Fetch settings
            minimum_step: 30000 # Must match opennms.interval
            heartbeat: 450000
            # Common settings
            ttl: 31540000
            ring_buffer_size: 4194304
            cache_max_entries: 2000000
            # Performance settings (crucial when using ScyllaDB)
            writer_threads: '{{ ansible_processor_cores * 2 }}'
            core_connections_per_host: 8 # Should be a factor of the number of Cores on a Scylla node.
            max_connections_per_host: 8 # Should be a factor of the number of Cores on a Scylla node.
            max_requests_per_connection: 8192
            compression: NONE # Options: LZ4, SNAPPY, NONE (default: NONE)
            max_batch_size: 32 # Must be consistent with batch_size_fail_threshold_in_kb (default: 16)
      hosts:
        opennms: # Ansible will run from here
          ansible_host: localhost
    cassandra_servers:
      vars:
        target_ipv4: '{{ ansible_eth0.ipv4.address }}'
        cassandra:
          vendor_repo: scylla # Options: scylla, apache
          repo_version: 4.1 # Apache: 311x, 40x; Scylla: 4.1
          cluster_name: OpenNMS
          replication_factor: 2
          batch_size_fail_threshold_in_kb: 50
          compaction_window_size: 7 # Must be consistent with opennms.newts.ttl
          compaction_window_unit: DAYS
          disk_devices:
          - /dev/sdc
          - /dev/sdd
      hosts: # Must cover size of cassandra_ip_addresses from vars.tf; assumes DNS, check cassandra.tf
        cassandra[1:3]: {}
    cortex_servers:
      vars:
        target_ipv4: '{{ ansible_eth0.ipv4.address }}'
        period_in_days: 7
        querier_max_concurrent: 1000
        cassandra_consistency: ONE
        cassandra_num_connections: 8 # Should be a factor of the number of Cores on a Scylla node.
      hosts: # Must cover size of cortex_ip_addresses from vars.tf; assumes DNS, check cortex.tf
        cortex[1:3]: {}
    nginx_servers:
      vars:
        target_ipv4: '{{ ansible_eth0.ipv4.address }}'
      hosts: # Assumes DNS, check cortex-nginx.tf
        cortex: {}
