##############################################################################
# Install and configure OpenNMS with PostgreSQL
# Author: Alejandro Galue <agalue@opennms.org>
##############################################################################

---
- name: Install OpenNMS with PostgreSQL
  hosts: onms_servers
  become: true
  tasks:
  - name: Install Dependencies
    package:
      state: present
      name:
      - java-11-openjdk-devel
      - postgresql-server
  - name: Initialize Database
    command: 'postgresql-setup initdb'
    args:
      creates: /var/lib/pgsql/data/pg_hba.conf
  - name: Update pg_hba.conf
    replace:
      path: /var/lib/pgsql/data/pg_hba.conf
      regexp: '(peer|ident)$'
      replace: 'trust'
      mode: '0644'
  - name: Apply tuning
    with_dict: '{{ postgresql.settings }}'
    replace:
      path: '/var/lib/pgsql/data/postgresql.conf'
      regexp: '^[#]?{{ item.key }} = [^\s]+'
      replace: '{{ item.key }} = {{ item.value }}'
      mode: '0600'
  - name: Start PostgreSQL Service
    service:
      name: postgresql
      state: started
      enabled: yes
  - name: Install the OpenNMS repository
    yum:
      state: present
      name: 'http://yum.opennms.org/repofiles/opennms-repo-{{ opennms.repo }}-rhel{{ ansible_distribution_major_version }}.noarch.rpm'
  - name: Install OpenNMS Packages
    package:
      state: present
      name:
      - rrdtool
      - jrrd2
      - opennms-core
      - opennms-webapp-jetty
      - opennms-webapp-hawtio
  - name: Copy Default Foreign Source
    copy:
      src: default-foreign-source.xml
      dest: /opt/opennms/etc/default-foreign-source.xml
      mode: '0644'
  - name: Copy Database Configuration
    template:
      src: opennms-datasources.xml.j2
      dest: /opt/opennms/etc/opennms-datasources.xml
      mode: '0644'
  - name: Copy Timeseries Configuration
    template:
      src: timeseries.properties.j2
      dest: /opt/opennms/etc/opennms.properties.d/timeseries.properties
      mode: '0644'
  - name: Copy JVM Properties
    template:
      src: opennms.conf.j2
      dest: /opt/opennms/etc/opennms.conf
      mode: '0644'
  - name: Update Cassandra credentials for Pollerd and Collectd
    replace:
      path: '{{ item }}'
      regexp: 'cassandra-(username|password)'
      replace: 'cassandra' # Must match cassandra.jmxremote.password
      mode: '0644'
    loop:
      - /opt/opennms/etc/collectd-configuration.xml
      - /opt/opennms/etc/poller-configuration.xml
  - name: Update polling and collection interval
    replace:
      path: '{{ item }}'
      regexp: 'interval="300000"'
      replace: 'interval="{{ opennms.interval }}"'
      mode: '0644'
    loop:
      - /opt/opennms/etc/collectd-configuration.xml
      - /opt/opennms/etc/poller-configuration.xml
  - name: Initialize OpenNMS Schema
    command: '/opt/opennms/bin/install -dis'
    args:
      creates: /opt/opennms/etc/configured
  - name: Install and configure Cortex
    when: tss_strategy == 'cortex'
    block:
    - name: Copy OIA TSS Plugin
      copy:
        src: opennms-cortex-tss-plugin.kar
        dest: /opt/opennms/deploy/opennms-cortex-tss-plugin.kar
        mode: '0644'
    - name: Enable OIA TSS Plugin
      copy:
        src: cortex.boot
        dest: /opt/opennms/etc/featuresBoot.d/cortex.boot
        mode: '0644'
    - name: Configura OIA TSS Plugin
      vars:
        cortex_srv: '{{ "cortex1" if groups.cortex_servers|length == 1 else "cortex" }}'
      template:
        src: org.opennms.plugins.tss.cortex.cfg
        dest: /opt/opennms/etc/org.opennms.plugins.tss.cortex.cfg
        mode: '0644'
  - name: Install Grafana
    yum:
      state: present
      name: 'https://dl.grafana.com/oss/release/grafana-{{ grafana.version }}-1.x86_64.rpm'
