##############################################################################
# Bootstrap process
# Author: Alejandro Galue <agalue@opennms.org>
##############################################################################

---
- name: Restart Cortex
  hosts: cortex_servers
  ignore_unreachable: true
  become: true
  tasks:
  - name: Restart Consul and Cortex
    service:
      name: '{{ item }}'
      state: restarted
      enabled: yes
    loop:
    - consul
    - cortex