##############################################################################
# Install and configure Nginx (a load balancer for Cortex)
# Author: Alejandro Galue <agalue@opennms.org>
##############################################################################

---
- name: Setup Nginx
  hosts: nginx_servers
  become: true
  tasks:
  - name: Install and configure Nginx
    when: tss_strategy == 'cortex'
    block:
    - name: Install Nginx
      package:
        state: present
        name:
        - nginx
    - name: Configure SELinux
      seport:
        ports: '{{ item }}'
        proto: tcp
        setype: http_port_t
        state: present
      loop:
      - 9009
      - 9095
    - name: Copy Load Balancer configuration
      template:
        src: '{{ item }}.j2'
        dest: /etc/nginx/conf.d/{{ item }}
        mode: '0644'
      loop:
      - cortex-web.conf
      - cortex-grpc.conf
