##############################################################################
# Common Settings for ALL the Machines
# Author: Alejandro Galue <agalue@opennms.org>
##############################################################################

---
- name: Common Configuration
  hosts: all
  become: true
  ignore_unreachable: true
  tasks:
  - name: Set timezone
    timezone:
      name: '{{ timezone }}'
  - name: Kernel Tuning
    with_dict: '{{ sysctl_config }}'
    sysctl:
      name: '{{ item.key }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  - name: Disable THP
    shell: 'set -o pipefail && echo "never" | tee /sys/kernel/mm/transparent_hugepage/{{ item }}'
    changed_when: False
    loop:
    - enabled
    - defrag
  - name: Install EPEL Repository
    package:
      state: present
      name:
      - epel-release
  - name: Install Dependencies
    package:
      state: present
      name:
      - git
      - vim
      - net-snmp
      - net-snmp-utils
      - jq
      - net-tools
      - dstat
      - htop
      - nmap-ncat
      - tree
      - telnet
      - curl
      - nmon
      - haveged
  - name: SNMP Configuration
    template:
      backup: yes
      src: snmpd.conf.j2
      dest: /etc/snmp/snmpd.conf
      mode: '0644'
  - name: Start snmpd Service
    service:
      name: snmpd
      state: started
      enabled: yes
  - name: Start haveged Service
    service:
      name: haveged
      state: started
      enabled: yes

