##############################################################################
# Install and configure Cassandra
# Author: Alejandro Galue <agalue@opennms.org>
##############################################################################

---
- name: Install Cassandra
  hosts: cassandra_servers
  become: true
  vars:
    raid_device: /dev/md0
  tasks:
  - name: Install Dependencies
    package:
      state: present
      name:
      - java-1.8.0-openjdk-devel
      - python2
      - parted
      - mdadm
      - patch
  - name: Initialize Disks
    parted:
      device: '{{ item }}'
      number: 1
      flags: [ raid ]
      state: present
    loop: '{{ cassandra.disk_devices }}'
  - name: Create RAID0 device at {{ raid_device }}
    shell: 'set -o pipefail && mdadm --create {{ raid_device }} --level=stripe --name=cassandra --raid-devices=2 {{ cassandra.disk_devices | join("1 ") }}1'
    args:
      creates: '{{ raid_device }}'
  - name: Create a xfs filesystem on {{ raid_device }}
    filesystem:
      fstype: xfs
      dev: '{{ raid_device }}'
  - name: Mount Cassandra Directory
    mount:
      path: /var/lib/cassandra
      src: '{{ raid_device }}'
      fstype: xfs
      opts: defaults,noatime
      state: mounted
      boot: yes
  - name: Install Cassandra Repository
    copy:
      src: files/cassandra.repo
      dest: /etc/yum.repos.d/cassandra.repo
  - name: Install Cassandra
    package:
      state: present
      name:
      - cassandra
      - cassandra-tools
  - name: Set cluster_name
    replace:
      path: /etc/cassandra/conf/cassandra.yaml
      regexp: '^(cluster_name:).*'
      replace: '\1 {{ cassandra.cluster_name }}'
  - name: Set listen_address
    replace:
      path: /etc/cassandra/conf/cassandra.yaml
      regexp: '^(listen_address:).*'
      replace: '\1 {{ cassandra.target_ipv4 }}'
  - name: Set rpc_address
    replace:
      path: /etc/cassandra/conf/cassandra.yaml
      regexp: '^(rpc_address:).*'
      replace: '\1 {{ cassandra.target_ipv4 }}'
  - name: Set seeds
    replace:
      path: /etc/cassandra/conf/cassandra.yaml
      regexp: '^(.*seeds:).*'
      replace: '\1 cassandra1'
  - name: Set concurrent_compactors
    replace:
      path: /etc/cassandra/conf/cassandra.yaml
      regexp: '^.*(concurrent_compactors:).*'
      replace: '\1 {{ ansible_processor_cores }}'
  - name: Set RMI Host
    replace:
      path: /etc/cassandra/conf/cassandra-env.sh
      regexp: '^.*(JVM_OPTS=.*rmi.server.hostname).*'
      replace: '\1={{ cassandra.target_ipv4 }}"'
  - name: Enable jmxremote.access
    replace:
      path: /etc/cassandra/conf/cassandra-env.sh
      regexp: '^[#](JVM_OPTS=".*jmxremote.access")'
      replace: '\1'
  - name: Disable LOCAL_JMX
    replace:
      path: /etc/cassandra/conf/cassandra-env.sh
      regexp: '^(.*LOCAL_JMX)=yes'
      replace: '\1=no'
  - name: Enable MAX_HEAP_SIZE
    replace:
      path: /etc/cassandra/conf/cassandra-env.sh
      regexp: '^[#](MAX_HEAP_SIZE)=.*'
      replace: '\1={{ (ansible_memtotal_mb / 2) | int }}M'
  - name: Enable HEAP_NEWSIZE
    replace:
      path: /etc/cassandra/conf/cassandra-env.sh
      regexp: '^[#](HEAP_NEWSIZE)=.*'
      replace: '\1={{ (ansible_memtotal_mb / 2) | int }}M'
  - name: Copy jvm.options
    copy:
      src: files/cassandra.jvm.options
      dest: /etc/cassandra/conf/jvm.options
  - name: Copy jmxremote.password
    copy:
      src: files/cassandra.jmxremote.password
      dest: /etc/cassandra/jmxremote.password
      owner: cassandra
      group: cassandra
      mode: '0400'
  - name: Copy jmxremote.access
    copy:
      src: files/cassandra.jmxremote.access
      dest: /etc/cassandra/jmxremote.access
      owner: cassandra
      group: cassandra
      mode: '0400'
  - name: Apply patch to /etc/init.d/cassandra
    patch: # https://issues.apache.org/jira/browse/CASSANDRA-15273
      src: files/cassandra.patch
      dest: /etc/init.d/cassandra
  - name: Copy Newts CQL file
    template:
      src: newts.cql.j2
      dest: /etc/cassandra/conf/newts.cql
