##############################################################################
# Install and configure OpenNMS with PostgreSQL
# Author: Alejandro Galue <agalue@opennms.org>
##############################################################################

---
- name: Install OpenNMS with PostgreSQL
  hosts: onms_servers
  become: true
  tasks:
  - name: Install Dependencies
    package:
      state: present
      name:
      - java-11-openjdk-devel
      - postgresql-server
  - name: Initialize Database
    command: 'postgresql-setup initdb'
    args:
      creates: /var/lib/pgsql/data/pg_hba.conf
  - name: Update pg_hba.conf
    replace:
      path: /var/lib/pgsql/data/pg_hba.conf
      regexp: '(peer|ident)$'
      replace: 'trust'
  - name: Start PostgreSQL Service
    service:
      name: postgresql
      state: started
      enabled: yes
  - name: Install the OpenNMS repository
    yum:
      state: present
      disable_gpg_check: yes
      name: 'http://yum.opennms.org/repofiles/opennms-repo-{{ opennms.repo }}-rhel{{ ansible_distribution_major_version }}.noarch.rpm'
  - name: Install OpenNMS Packages
    package:
      state: present
      name:
      - rrdtool
      - jrrd2
      - opennms-core
      - opennms-webapp-jetty
      - opennms-webapp-hawtio
  - name: Copy Default Foreign Source
    copy:
      src: default-foreign-source.xml
      dest: /opt/opennms/etc/default-foreign-source.xml
  - name: Copy Newts Configuration
    template:
      src: newts.properties.j2
      dest: /opt/opennms/etc/opennms.properties.d/newts.properties
  - name: Copy JVM Properties
    template:
      src: opennms.conf.j2
      dest: /opt/opennms/etc/opennms.conf
  - name: Update Cassandra credentials for Pollerd and Collectd
    replace:
      path: '{{ item }}'
      regexp: 'cassandra-(username|password)'
      replace: 'cassandra' # Must match cassandra.jmxremote.password
    loop:
      - /opt/opennms/etc/collectd-configuration.xml
      - /opt/opennms/etc/poller-configuration.xml
  - name: Update polling and collection interval
    replace:
      path: '{{ item }}'
      regexp: 'interval="300000"'
      replace: 'interval="{{ opennms.interval }}"'
    loop:
      - /opt/opennms/etc/collectd-configuration.xml
      - /opt/opennms/etc/poller-configuration.xml
  - name: Initialize OpenNMS Schema
    command: '/opt/opennms/bin/install -dis'
    args:
      creates: /opt/opennms/etc/configured

