##############################################################################
# Install and configure Scylla
# Author: Alejandro Galue <agalue@opennms.org>
##############################################################################

---
- name: Setup Scylla
  hosts: cassandra_servers
  become: true
  tasks:
  - name: Install and configure Scylla
    when: cassandra.vendor_repo == 'scylla'
    block:
    - name: Install Repository
      uri:
        url: 'http://downloads.scylladb.com/rpm/centos/scylla-{{ cassandra.repo_version }}.repo'
        creates: /etc/yum.repos.d/scylla.repo
        dest: /etc/yum.repos.d/scylla.repo
    - name: Install Scylla
      package:
        state: present
        name: scylla
    - name: Configure Scylla
      shell: 'set -o pipefail && scylla_setup --disks {{ cassandra.disk_devices | join(",") }} --no-version-check'
      args:
        creates: /dev/md0
    - name: Copy Newts CQL file
      template:
        src: newts.cql.j2
        dest: /etc/scylla/newts.cql
    - name: Set cluster_name
      replace:
        path: /etc/scylla/scylla.yaml
        regexp: '^[#]?(cluster_name:).*'
        replace: '\1 {{ cassandra.cluster_name }}'
    - name: Set listeners
      replace:
        path: /etc/scylla/scylla.yaml
        regexp: '^({{ item }}:).*'
        replace: '\1 {{ cassandra.target_ipv4 }}'
      loop:
      - listen_address
      - rpc_address
      - api_address
    - name: Set batch_size_fail_threshold_in_kb
      replace:
        path: /etc/scylla/scylla.yaml
        regexp: '^(batch_size_fail_threshold_in_kb:).*'
        replace: '\1 {{ cassandra.batch_size_fail_threshold_in_kb }}'
    - name: Set cassandra1 as seed node
      replace:
        path: /etc/scylla/scylla.yaml
        regexp: '^(.*seeds:).*'
        replace: '\1 "cassandra1"'
    # The following doesn't seem to be used
    - name: Set RMI Host
      replace:
        path: /etc/scylla/cassandra/cassandra-env.sh
        regexp: '^.*(JVM_OPTS=.*rmi.server.hostname).*'
        replace: '\1={{ cassandra.target_ipv4 }}"'
    - name: Enable jmxremote.access
      replace:
        path: /etc/scylla/cassandra/cassandra-env.sh
        regexp: '^[#](JVM_OPTS=".*jmxremote.access")'
        replace: '\1'
    - name: Disable LOCAL_JMX
      replace:
        path: /etc/scylla/cassandra/cassandra-env.sh
        regexp: '^(.*LOCAL_JMX)=yes'
        replace: '\1=no'
    - name: Fix JMX remote paths
      replace:
        path: /etc/scylla/cassandra/cassandra-env.sh
        regexp: 'etc\/cassandra'
        replace: 'etc/scylla'
    - name: Copy jmxremote.password
      copy:
        src: cassandra.jmxremote.password
        dest: /etc/scylla/jmxremote.password
        owner: scylla
        group: scylla
        mode: '0400'
    - name: Copy jmxremote.access
      copy:
        src: cassandra.jmxremote.access
        dest: /etc/scylla/jmxremote.access
        owner: scylla
        group: scylla
        mode: '0400'
